version: 0.2

phases:
  pre_build:
    commands:
      - if [ -s /home/ec2-user/.nvm/nvm.sh ]; then source /home/ec2-user/.nvm/nvm.sh; fi
      - npm install
  build:
    commands:
      - cd /home/ec2-user/test-asai/aj1-app
      - npm run build
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - "**/*"
  base-directory: build
cache:
  paths:
    - /tmp/node_modules.tar
